meson.build: require native iso-codes
I have seen a cross compilation error from a host that does not provide iso-codes

FAILED: app/widgets/gimplanguagestore-data.h
/mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/gimp/3.0.2/build/tools/gen-languages
gimp_language_store_parser_init: 0.006277 seconds
ERROR: parse_iso_codes: error parsing '/usr/share/xml/iso-codes/iso_639_3.xml': No such file or directory

The problem could be fixed by making 'iso-codes' a build machine dependency

Signed-off-by: Markus Volk <f_l_k@t-online.de>